version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    container_name: ${PROJECT_SLUG}_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_dir:/app/static/
      - media_dir:/app/media/
      - ./backend/:/app/
    env_file:
      - .env
    expose:
      - '8000'
    ports:
      - '8000:8000'
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    container_name: ${PROJECT_SLUG}_frontend
    expose:
      - '3001'
    volumes:
      - ./frontend:/usr/src/app

  db:
    image: postgres:13
    container_name: ${PROJECT_SLUG}_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - '5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    container_name: ${PROJECT_SLUG}_nginx
    volumes:
      - static_dir:/app/src/static/
      - media_dir:/app/src/media/
    ports:
      - '80:80'
    depends_on:
      - app
      - frontend

volumes:
  static_dir:
  media_dir:
  db_data:
