# Generated by Django 5.1 on 2024-08-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_remove_photo_is_favorite'),
        ('users', '0003_parent_favorite_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='favorite_photos',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='favorite_photos',
            field=models.ManyToManyField(blank=True, related_name='favorite_for', to='photos.photo'),
        ),
    ]
