# Generated by Django 5.1 on 2024-08-31 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customer_manager_remove_baseuser_favorite_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='name',
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='name',
        ),
    ]
