# Generated by Django 5.1 on 2024-09-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_manager_bank_card_alter_manager_tin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
    ]
