# Generated by Django 5.1 on 2024-08-31 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_remove_photo_is_favorite'),
        ('users', '0005_customer_manager_remove_baseuser_favorite_photos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='school_class',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='upload_at',
            new_name='uploaded_on',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.CreateModel(
            name='PhotoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('customers', models.ManyToManyField(to='users.customer')),
                ('photographer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_sessions', to='users.photographer')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.photosession'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PhotosPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_code', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_purchases', to='users.customer')),
                ('pickup_hub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos_purchases', to='photos.pickuphub')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='photos_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='photos.photospurchase'),
        ),
        migrations.DeleteModel(
            name='SchoolClass',
        ),
    ]
