# Generated by Django 5.1 on 2024-09-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_pickuphub_remove_photo_school_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosession',
            name='address',
            field=models.CharField(default='GoStarStar, main st, 83', max_length=100),
            preserve_default=False,
        ),
    ]
