# Generated by Django 5.1 on 2024-09-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photosession_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosession',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
