# Generated by Django 5.1 on 2024-09-15 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_photosession_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photospurchase',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='photospurchase',
            name='pickup_hub',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photos_purchase',
        ),
        migrations.DeleteModel(
            name='PickupHub',
        ),
        migrations.DeleteModel(
            name='PhotosPurchase',
        ),
    ]
